### ISSUE TITLE
Title: App is showing “City”, “State” and “Country” fields as a simple text field whereas as per client’s requirements it should be choose able  

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#10]
Screen Name: Let’ create your profile 2
Build version: 1.0 

Actual result: You will note that app not showing any dropdown for “City”, “State” and “Country” fields from where he can choose the results.
Expected result: Ideally app should show the Drop-Down menus for these fields or these fields should be connected with Google map and app should show the map suggestions to select.

Refer this screenshot/video: https://www.screencast.com/t/inhcXPcE3q 
Refer this client’s requirement: https://www.screencast.com/t/btzWCVIoFH

**Comment by Aqurds** [comment]
@sallarrezaie this bug is fixed.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and now app is showing Country field drop-down menu with countries list.
