### ISSUE TITLE
Title: “Zip code” text field is accepting other characters too whereas client’s requirement is only Numeric for this field

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#11]
Screen Name: Let’ create your profile 3
Build version: 1.0 

Actual result: “Zip code” text field is accepting other characters too whereas client’s requirement is only Numeric for this field.
Expected result: Ideally Zip code field should only accept Numeric characters.

Refer this screenshot/video: https://www.screencast.com/t/xB7AKsYwmfR 
Refer this client’s requirement: https://www.screencast.com/t/50k9brtWjWRr

**Comment by Aqurds** [comment]
@Sheerazzafar "Zipcode" text field is now only accepting numbers. This bug is fixed.

**Comment by cavespoint** [comment]
Good morning.

Just a quick note to let you know not all countries have only number zip codes.

Regards,

J. Ignacio García

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
