### ISSUE TITLE
Title: App is not showing “Address” text field

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#12]
Screen Name: Let’s create your profile 3
Build version: 1.0 

Actual result: App is not showing Address text field as per client’s requirement.
Expected result: Ideally app should show Address field as per client’s requirement.

Refer this client’s requirement: https://www.screencast.com/t/TYHQpBk6 
Refer this Figma: https://www.screencast.com/t/JXRQSUZw

**Comment by Aqurds** [comment]
@Sheerazzafar "Address" text field added and functional.

**Comment by Sheerazzafar** [comment]
Verified this issue on the latest build and this issue is fixed now!
