### ISSUE TITLE
Title: App is showing text field for the Birth Day field

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#13]
Screen Name: Let’s create your profile 3
Build version: 1.0 

Actual result: App is showing text field for the Birth Day field.
Expected result: Ideally app should show the calendar for selecting the Birth Day.

Refer this screenshot/video: https://www.screencast.com/t/1GuvQ11iv

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed.

**Comment by Sheerazzafar** [comment]
This issue is fixed now on the latest build but now user is able to select the future date in the DOB field.

**Comment by Aqurds** [comment]
@Sheerazzafar point noted

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
