### ISSUE TITLE
Title: App is not showing drop-down menu for the Gender field

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#14]
Screen Name: Let’s create your profile 3
Build version: 1.0 

Actual result: App is not showing drop-down menu for the Gender field.
Expected result: Ideally app should show drop-down menu for selecting the Gender.
Refer this screenshot/video: https://www.screencast.com/t/1GuvQ11iv 
Refer this Figma: https://www.screencast.com/t/NIzBFyhq

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed!
