### ISSUE TITLE
Title: App is accepting multiple characters in the single box of OTP

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#15]
Screen Name: Forgot Password
Build version: 1.0 

Actual result: App is accepting multiple characters in the single box of OTP.
Expected result: Ideally app should only accept 1 digit in 1 box and after entering digit app should take user to the next box.
Refer this screenshot/video: https://www.screencast.com/t/63md9MB2eMU

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed. Now the single box is excepting only 1 character and the next box is automatically focused.

**Comment by Sheerazzafar** [comment]
Unable to test this issue due to previous screen issue.

**Comment by Aqurds** [comment]
@Sheerazzafar this bug should be tested now. Thanks.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
