### ISSUE TITLE
Title: App is showing 5 digit in the OTP box as default as placeholder text

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#16]
Screen Name: Forgot Password
Build version: 1.0 

Actual result: App is showing 5 digit in the OTP box as default as placeholder text.
Expected result: Ideally app should not show placeholder text in the OTP field.

Refer this screenshot/video: https://www.screencast.com/t/V6GnFoVUt

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed.

**Comment by Sheerazzafar** [comment]
Not able to reach at this screen, I will test it when the previous screen issue gets fixed.

**Comment by Aqurds** [comment]
@Sheerazzafar this bug should be tested now. Thanks.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
