### ISSUE TITLE
Title: App is not showing “Resend” link on the OTP verification screen

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#17]
Screen Name: Forgot Password
Build version: 1.0 

Actual result: App is not showing “Resend” link on the OTP verification screen.
Expected result: Ideally app should show Resend link on the OTP verification screen.

Refer this screenshot/video: https://www.screencast.com/t/PCmpmuIxP 
Refer this Figma: https://www.screencast.com/t/tUPgU09eWYt

**Comment by Aqurds** [comment]
@sallarrezaie this bug is fixed.

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
I have verified this issue on latest build and another issue is happening before this screen. Please fix the issue.
Title: App shows "Email sent with token" message continuously when user submit the email.
Screenshot: https://www.screencast.com/t/363gA6mKWX

**Comment by Aqurds** [comment]
Hi @Sheerazzafar, I haven't understood the point here. Would you please show me a video explanation?

**Comment by Aqurds** [comment]
@Sheerazzafar I got this issue. It was not a bug, you input an email that doesn't exist in any account. But, the lacking was, that I didn't implement any error message if a user inputs the wrong email. Now, it should work. With a working email, you will get to the OTP screen and with the wrong email, you will get an alert.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
