### ISSUE TITLE
 Title: After sign up successfully app takes user to the Location screen instead of Upload profile picture screen

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#18]
Screen Name: Signup
Build version: 1.0 

Actual result: App is not redirecting user to the Upload Profile Picture screen. 
Expected result: Ideally app should redirect to the Upload Profile Picture screen after Sign up successfully.
Refer this screenshot/video: https://www.screencast.com/t/4j2q0mXZ9o

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
