### ISSUE TITLE
Your Name and Phone Number disappear

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#19]
When you continue from LCP 2 to 3, if you go back to LCP 2, Your Name and Phone MNUmber have disappear. Have to write them again. You cannot go back to check info, and go forward to LCP 3

provided by the customer

@Sheerazzafar pls validate if it is being reproduced and assign to a dev to fix

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
I have verified this issue at my end and only "Your name" entry gets disappear. Please fix it as per client's requirement.
Expected: You cannot go back to check info, and go forward to LCP 3.

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
I have verified this issue and the same issue is still happening as mentioned in the above comment.

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
I have verified this issue at my end and only "Your name" entry gets disappear. Please fix it as per client's requirement.
Expected: You cannot go back to check info, and go forward to LCP 3.
Here is the video: https://www.screencast.com/t/dBPquVzV

**Comment by romangorbunovCB** [comment]
@Sheerazzafar the expected behavior is that the user is able to get back, but the name must stay. 

@Aqurds the bug is remaining after the third testing approach. What problems are you experiencing with that bug?

**Comment by Aqurds** [comment]
@romangorbunovCB I'm rechecking it, maybe caching issue not reflecting the latest changes.

**Comment by romangorbunovCB** [comment]
@asim-crowdbotics pls proceed with these issues as well

**Comment by asim-crowdbotics** [comment]
Should be resolved in the latest APK, as the flow has been fixed for the onboarding.

**Comment by romangorbunovCB** [comment]
@Sheerazzafar pls confirm if the issue is fixed and update the ticket.

**Comment by Sheerazzafar** [comment]
Verified this issue and its fixed now!
