### ISSUE TITLE
Remove number 3

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#20]
Let’s Create your Profile (Screen 3)
Please removed number 3, inconsistent as said numbers don’t appear in first two screens.

provided by the customer

![screenshot-nimbusweb me-2022 08 01-20_57_36](https://user-images.githubusercontent.com/89276920/182212150-a10f9044-dbe9-48b2-a96a-ca97cb7316b5.png)

**Comment by Sheerazzafar** [comment]
@Aqurds please remove it as per client's requirement and let me know when its fixed!

**Comment by Aqurds** [comment]
@Sheerazzafar it's fixed

**Comment by Sheerazzafar** [comment]
Verified and this issue is fixed now!
