### ISSUE TITLE
Birthday: Field is blank

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#21]
Let’s Create your Profile (Screen 3)
Birthday:
Field is blank, should Say: Date of Birth - (Optional)

Provided by the customer
![screenshot-nimbusweb me-2022 08 01-21_04_58](https://user-images.githubusercontent.com/89276920/182213273-f396553f-c08b-42ac-8011-da841f02d81e.png)

Expected
![screenshot-www figma com-2022 08 01-21_06_34](https://user-images.githubusercontent.com/89276920/182213420-19afe273-8af2-4f9e-b406-fb9087171d3e.png)

**Comment by Sheerazzafar** [comment]
@Aqurds "Date of Birth" field should show placeholder text as mentioned above. 
Placeholder text: Date of Birth - (Optional)

**Comment by Aqurds** [comment]
@Sheerazzafar it's fixed.

**Comment by Sheerazzafar** [comment]
Verified and this issue is fixed now!
