### ISSUE TITLE
invert fields on Home Location:

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#27]
Country
As an idea to simplify process. We could invert fields on Home Location:. List Fields in the following order
Country
ZIP Code
City
State (Optional)
Adress (Optional)

provided by the customer.
not on prd, okay to go

**Comment by Aqurds** [comment]
@Sheerazzafar this is fixed. cc @romangorbunovCB

**Comment by Sheerazzafar** [comment]
Verified and this task is implemented as per mentioned in the task description!
