### ISSUE TITLE
When user tries to add any place to My Places than app shows "Network error Failed" error and due to this issue I am not able to test the Other User profile Tab 1

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#38]
Device: Samsung s9 Plus
Build version: Android 153

Actual result: When user tries to add any place to My Places than app shows "Network error Failed" error.
Expected result: Ideally user should be able to add My places successfully.
Video: https://www.screencast.com/t/PgI2xVqnBHJK

**Comment by romangorbunovCB** [comment]
It works fine for me both for adding to My Places and to Explore. 
@Sheerazzafar pls confirm if it is being reproduced at your device.

**Comment by sallarrezaie** [comment]
This works for me as well. Network error may just be a problem with the network connection on the device.

**Comment by Sheerazzafar** [comment]
Verified this issue and its fixed now!
