### ISSUE TITLE
App is showing “Bucket List” empty app is not showing any data there and Figma is not matching as per PRD

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#39]
Device: Samsung s9 Plus
Build version: Android 153

Actual result: App is showing “Bucket List” empty app is not showing any data there and Figma is not matching as per PRD.
Expected result: Ideally app should show data in the bucket list as per PRD.

Screenshot app: https://www.screencast.com/t/Npa6YUTov
Figma: https://www.screencast.com/t/ROICUxGYlm
PRD:  https://www.screencast.com/t/mx7mJY07aqqU

Note: Please add the details that what is correct Figma or PDR?

**Comment by asim-crowdbotics** [comment]
@romangorbunovCB Please review

**Comment by romangorbunovCB** [comment]
@Sheerazzafar did you check if the user added any places to his bucket list. this condition must be confirmed, otherwise no data should be displayed. 
cc: @asim-crowdbotics

**Comment by asim-crowdbotics** [comment]
https://user-images.githubusercontent.com/111840959/194308655-4cf4e14b-d710-4b43-938b-6b4b06d2d329.MP4

**Comment by sallarrezaie** [comment]
@romangorbunovCB , as long as the user has added places to their bucket list there should be those places returned. If they haven't added anything to their bucket list, there would be nothing to return.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
