### ISSUE TITLE
Placeholder text in the Search field is getting cut-off

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#40]
Device: Samsung s9 Plus
Build version: Android 153

Actual result: Placeholder text in the Search field is getting cut-off.
Expected result: Ideally app should not show cut-off issue.
Screenhsot: https://www.screencast.com/t/q9sywjZ5Si

**Comment by romangorbunovCB** [comment]
It works fine for me as well. 
@Sheerazzafar pls try to reproduce. 

![photo_2022-10-06_16-23-43](https://user-images.githubusercontent.com/89276920/194324494-2ce96fad-fb97-446c-aee9-1e989e305c07.jpg)

**Comment by Sheerazzafar** [comment]
Verified this issue and its fixed now!
