### ISSUE TITLE
Title: User is not able to search any user by “User name”

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#41]
Build: Android 153
Screen Name: Search
Device: Samsung s9 Plus

Actual result: User is not able to search any user by ”User name”.
Expected result: Ideally user should be able to search any user by their “User Name”.

Refer this Screenshot/Video: https://www.screencast.com/t/VKG8sM32uA

**Comment by asim-crowdbotics** [comment]
There is no username. There is only Name and email of the user. We are searching based on name of the user. 

Username shown on the app is generated by removing spaces from the name just to fulfill the figma design requirements.
@romangorbunovCB

**Comment by romangorbunovCB** [comment]
@asim-crowdbotics 
I see this requirement in the PRD

>Acceptance Criteria:
As a User type, I would be able to search users by User name or by Real name.

@Sheerazzafar Feel free to quote a line from the PRD or a piece of design to refer to a particular point of the issue for the next cases.

**Comment by asim-crowdbotics** [comment]
@romangorbunovCB backend does not support usernames as far as I know. Please correct me if I am wrong @sallarrezaie.

**Comment by sallarrezaie** [comment]
@asim-crowdbotics you are correct it did not support Username as the signup was only using Email, Name and Password. It seems they'd like the user to be able to add a Username in their profile setup. I will add this into the Update Profile endpoint now and let you know once it is ready

**Comment by sallarrezaie** [comment]
@asim-crowdbotics , you can update the username in the Update profile API but it wasn't being returned nor was it searchable in the List Users API. 

I've just created a pull request that has added this feature in. The users will name also return with a username field and you can now search using the "search" query parameter in the List Users API. This search parameter will search both Name and Username, returning matching results. Please let me know if you have any questions. 

@romangorbunovCB , this should be resolved form the backend and just needs the pull request merged so I can deploy

**Comment by romangorbunovCB** [comment]
@sallarrezaie it is merged. pls, deploy. thank you.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
