### ISSUE TITLE
Social sign up does not work

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#46]
**Now**
When I proceed to signup with Facebook
Then I get the error message

![photo_2022-09-30_17-11-47](https://user-images.githubusercontent.com/89276920/193288904-df380db5-b531-415e-b3f9-8ce320e3e581.jpg)

When I proceed to signup with Google, Apple
Then nothing happens

**Expected**
As a User type, I would be able to use social sign up:
- Google
- Apple
- Facebook

**Comment by asim-crowdbotics** [comment]
@romangorbunovCB  There is no implementation of social login in the application. Facebook login has incomplete integration done and hence shows this error.

**Comment by romangorbunovCB** [comment]
@asim-crowdbotics what do we need in order to have? pls provide details

**Comment by sallarrezaie** [comment]
@asim-crowdbotics Google and Facebook login is working for me locally, let me know if you need anything from my end

@romangorbunovCB , APIs for Google and Facebook are working as far as I know - but for Apple we'd need to set and save some data on the client's Apple developer account. Here's a working reference to the social logins module by CB, you'll find instructions for the data we need from apple under the Apple section

https://github.com/crowdbotics-apps/ideapros-llc-viaggi-32125/tree/sallar-fixes/backend/modules/social-auth

**Comment by romangorbunovCB** [comment]
Closing it down as it repeats [issue #4](https://github.com/crowdbotics-apps/ideapros-llc-viaggi-32125/issues/4)
