### ISSUE TITLE
The app does not redirect to the home screen after login

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#49]
**Now:**
Given I provided my credentials to login
And my credential are correct
When I proceed to login
Then I see the processing animation
But the app does not redirect me to the home screen
And I stay on the same login page

**Expected:**
Given I provided my credentials to login
And my credential are correct
When I proceed to login
Then I see the processing animation if it takes more than 500 ms to redirect
And the app redirects me to the home screen

**Comment by asim-crowdbotics** [comment]
https://user-images.githubusercontent.com/111840959/194301430-d82657a6-fe6c-42b7-b81e-c7327e2f79cd.MP4

**Comment by romangorbunovCB** [comment]
> RPReplay_Final1665051344.MP4

However I tried it many times from my device and it is still crashing. @Sheerazzafar Can you confirm or comment pls?

**Comment by asim-crowdbotics** [comment]
@romangorbunovCB Can you please share a video recording if possible?

**Comment by romangorbunovCB** [comment]
@Sheerazzafar pls check at your side and update the issues.

**Comment by Sheerazzafar** [comment]
Verified this issue on the latest build and this issue is fixed now!
