### ISSUE TITLE
Keep the search input in the search field after search results are displayed

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#55]
**Now:**
Given I provided a search request input to the search field
When I confirm to proceed to the search
Then the system displays search results
And I am NOT able to see search request input to the search field

![photo_2022-10-11_17-34-55](https://user-images.githubusercontent.com/89276920/195120671-007d617d-933e-48c0-8ba7-21c0acbc1fa2.jpg)

**Expected:**
Given I provided a search request input to the search field
When I confirm to proceed to the search
Then the system displays search results
And I am able to see search request input to the search field

**Comment by Sheerazzafar** [comment]
Verified this issue on the latest build and the issue is fixed as per expecteed result!
