### ISSUE TITLE
Title: App is showing “Don’t have an account” text on the Sign up screen instead of “Already have an account”

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#6]
Screen Name: Sign Up
Build version: 1.0 

Actual result: App is showing “Don’t have an account” text on the Sign up screen instead of “Already have an account”.
Expected result: Ideally app should show “Already have an account” text as per Figma design.
Refer this screenshot/video: https://www.screencast.com/t/5xtgHo7qZ0 
Refer this Figma: https://www.screencast.com/t/gPJeK0nYlW

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
