### ISSUE TITLE
Title: App is showing “Authorization denied” error and not able to see the other screens when user Allow the Location

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#7]
Screen Name: Enable Location
Build version: 1.0 

Actual result: App is showing “Authorization denied” error and not able to see the other screens when user Allow the Location.
Expected result: Ideally app not show this error and user should be able to go to next screens.
Refer this screenshot/video: https://www.screencast.com/t/eD88qGF2tt08

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed.

**Comment by Sheerazzafar** [comment]
Verified this issue and now this error is not appearing, but app is also not redirecting to the next screen as per @Aqurds message that Home screen will be implemented in next milestone.

cc: @romangorbunovCB
