### ISSUE TITLE
Title: App is getting crash when don’t upload any profile photo and closes the gallery 

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#8]
Screen Name: Upload Profile picture
Build version: 1.0 

Seps to reproduce:
1: Launch the app
2: Sign up with valid credentials
3: Don’t Upload profile picture and come back to the Upload Profile picture screen

Actual result: App is getting crash when don’t upload any profile photo and closes the gallery.
Expected result: Ideally app should not crash.
Refer this screenshot/video: https://www.screencast.com/t/vQngIV3cV

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed.

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
