### ISSUE TITLE
Title: App is accepting the more than 200 characters in the Bio text field

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#9]
Screen Name: Let’ create your profile 1
Build version: 1.0 

Actual result: App is accepting the more than 200 characters in the Bio text field.
Expected result: Ideally app should accept only 200 characters in the Bio text field.
Refer this screenshot/video: https://www.screencast.com/t/zPIdmuOywTe 

Note: Due to this issue the above text is getting cut-off please also fix it.

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed.

**Comment by Sheerazzafar** [comment]
Verified and this issue is fixed now!
